### ISSUE TITLE
bug in type wrapper

### ISSUE THREAD

**Issue by gucio321** [AllenDang/cimgui-go#149]
add the following code:
```diff
diff --git a/examples/main.go b/examples/main.go
index 75afab3..1ced177 100644
--- a/examples/main.go
+++ b/examples/main.go
@@ -100,6 +100,10 @@ func afterCreateContext() {
 }
 
 func loop() {
+	fonts := imgui.CurrentIO().Fonts()
+	builder := imgui.NewFontGlyphRangesBuilder()
+	builder.AddRanges(fonts.GlyphRangesDefault())
+
 	showWidgetsDemo()
 	showPictureLoadingDemo()
 	showImPlotDemo()

```

it will crash with panic:
```console
unexpected fault address 0x9566b2
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x9566b2 pc=0x59a58a]

goroutine 1 [running, locked to thread]:
runtime.throw({0x918871?, 0xc000073ba8?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc000073b80 sp=0xc000073b50 pc=0x52191d
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:851 +0x28a fp=0xc000073be0 sp=0xc000073b80 pc=0x535e8a
github.com/AllenDang/cimgui-go.FontGlyphRangesBuilder.AddRanges.func2()
	/home/me/git/cimgui-go/type_wrapper.go:47 +0xa fp=0xc000073be8 sp=0xc000073be0 pc=0x59a58a
github.com/AllenDang/cimgui-go.FontGlyphRangesBuilder.AddRanges(0x18caeb0?, 0x9566b2?)
	/home/me/git/cimgui-go/cimgui_funcs.go:699 +0xb5 fp=0xc000073c48 sp=0xc000073be8 pc=0x59a4b5
main.loop()
	/home/me/git/cimgui-go/examples/main.go:105 +0x67 fp=0xc000073c78 sp=0xc000073c48 pc=0x5a6cc7
github.com/AllenDang/cimgui-go.loopCallback()
	/home/me/git/cimgui-go/backend.go:21 +0x3d fp=0xc000073c90 sp=0xc000073c78 pc=0x59a19d
_cgoexp_e0e0f9441f99_loopCallback(0x59a2bd?)
	_cgo_gotypes.go:76102 +0x17 fp=0xc000073ca0 sp=0xc000073c90 pc=0x59e097
runtime.cgocallbackg1(0x59e080, 0xc000073e50?, 0x0)
	/usr/local/go/src/runtime/cgocall.go:315 +0x2b1 fp=0xc000073d68 sp=0xc000073ca0 pc=0x4f3831
runtime.cgocallbackg(0xc0000061a0?, 0x300000002?, 0xc0000061a0?)
	/usr/local/go/src/runtime/cgocall.go:234 +0x109 fp=0xc000073df8 sp=0xc000073d68 pc=0x4f34e9
runtime.cgocallbackg(0x59e080, 0x7ffd1dedc98f, 0x0)
	<autogenerated>:1 +0x2f fp=0xc000073e20 sp=0xc000073df8 pc=0x550e8f
runtime.cgocallback(0x4f3365, 0x5d6610, 0xc000073eb0)
	/usr/local/go/src/runtime/asm_amd64.s:998 +0xb4 fp=0xc000073e48 sp=0xc000073e20 pc=0x54e754
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:463 fp=0xc000073e50 sp=0xc000073e48 pc=0x54c760
runtime.cgocall(0x5d6610, 0xc000073eb0)
	/usr/local/go/src/runtime/cgocall.go:167 +0x85 fp=0xc000073e88 sp=0xc000073e50 pc=0x4f3365
github.com/AllenDang/cimgui-go._Cfunc_igRunLoop(0x104e7f0, 0x5a6fc0, 0x5a7000, 0x5a7040, 0x5a70c0)
	_cgo_gotypes.go:27395 +0x45 fp=0xc000073eb0 sp=0xc000073e88 pc=0x598c85
github.com/AllenDang/cimgui-go.(*GLFWBackend).Run.func1(0xc000016410?)
	/home/me/git/cimgui-go/glfw_backend.go:92 +0x9f fp=0xc000073f10 sp=0xc000073eb0 pc=0x59cc7f
github.com/AllenDang/cimgui-go.(*GLFWBackend).Run(0xc0000a0180?, 0x91b295?)
	/home/me/git/cimgui-go/glfw_backend.go:92 +0x33 fp=0xc000073f28 sp=0xc000073f10 pc=0x59cbb3
main.main()
	/home/me/git/cimgui-go/examples/main.go:135 +0x1e2 fp=0xc000073f80 sp=0xc000073f28 pc=0x5a6f22
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x207 fp=0xc000073fe0 sp=0xc000073f80 pc=0x524207
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000073fe8 sp=0xc000073fe0 pc=0x54e981

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000060fb0 sp=0xc000060f90 pc=0x524636
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:305 +0xb0 fp=0xc000060fe0 sp=0xc000060fb0 pc=0x524470
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000060fe8 sp=0xc000060fe0 pc=0x54e981
created by runtime.init.6
	/usr/local/go/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000061780 sp=0xc000061760 pc=0x524636
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc0000617c8 sp=0xc000061780 pc=0x51126e
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc0000617e0 sp=0xc0000617c8 pc=0x506746
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000617e8 sp=0xc0000617e0 pc=0x54e981
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000088000?, 0x939b28?, 0x1?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000061f70 sp=0xc000061f50 pc=0x524636
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0xab1900)
	/usr/local/go/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000061fa0 sp=0xc000061f70 pc=0x50f1b3
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:628 +0x45 fp=0xc000061fc8 sp=0xc000061fa0 pc=0x50f785
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc000061fe0 sp=0xc000061fc8 pc=0x5066e6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000061fe8 sp=0xc000061fe0 pc=0x54e981
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x1a0?, 0xab1d40?, 0x60?, 0x78?, 0xc000060770?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000060628 sp=0xc000060608 pc=0x524636
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:193 +0x107 fp=0xc0000607e0 sp=0xc000060628 pc=0x505787
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000607e8 sp=0xc0000607e0 pc=0x54e981
created by runtime.createfing
	/usr/local/go/src/runtime/mfinal.go:163 +0x45
exit status 2
```

**Comment by ptxmac** [comment]
I hit that too, seems to be after wchar was added as a rune a few weeks ago

**Comment by ptxmac** [comment]
This seems a bit sketchy: https://github.com/AllenDang/cimgui-go/commit/074e16690b42a47f51a1323667fa80046b422d00

a golang rune is 32 bit

**Comment by ptxmac** [comment]
I've created a vert in #150 which puts the old behaviour back

**Comment by gucio321** [comment]
ok, works now, thank you again!
