### ISSUE TITLE
cimplot doesn't work

### ISSUE THREAD

**Issue by gucio321** [AllenDang/cimgui-go#36]
Hi!
cimplot wrapper doesn't seem to work at all:
```go
package main

import (
	"github.com/AllenDang/cimgui-go"
	"github.com/AllenDang/giu"
)

func loop() {
	giu.SingleWindow().Layout(
		giu.Label("my plot"),
		giu.Custom(func() {
			if cimgui.Plot_BeginPlot("my plot") {
				//cimgui.Plot_PlotBars_FloatPtrInt("my plot!", []float32{50}, 1)
				//c := cimgui.Plot_GetPlotDrawList()
				//cmds := c.Commands()
				//cr := cmds[len(cmds)-1].GetClipRect()
				//out := cimgui.ImVec2{}
				//cimgui.Plot_PlotToPixels_double(&out, float64(cr.X), float64(cr.Y))
				//fmt.Println(out)
				cimgui.Plot_EndPlot()
			}
		}),
	)
}

func main() {
	wnd := giu.NewMasterWindow("Labels on plot", 640, 480, 0)
	wnd.Run(loop)
}
```

```console
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x69a504]

runtime stack:
runtime.throw({0x97f25e?, 0xc0000061a0?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7fff8b400210 sp=0x7fff8b4001e0 pc=0x50d97d
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:819 +0x369 fp=0x7fff8b400260 sp=0x7fff8b400210 pc=0x5233a9

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x646f90, 0xc00015fb60)
	/usr/local/go/src/runtime/cgocall.go:158 +0x5c fp=0xc00015fb38 sp=0xc00015fb00 pc=0x4dcb5c
github.com/AllenDang/cimgui-go._Cfunc_Plot_BeginPlot(0x19af0a0)
	_cgo_gotypes.go:45509 +0x45 fp=0xc00015fb60 sp=0xc00015fb38 pc=0x596e85
github.com/AllenDang/cimgui-go.Plot_BeginPlot({0x9752fd?, 0x3000000030?})
	/home/mszeptuch/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20221018030210-b4e0125a30eb/cimplot_funcs.go:1660 +0x4b fp=0xc00015fb90 sp=0xc00015fb60 pc=0x5999cb
main.loop.func1()
	/home/mszeptuch/git/giu/examples/label-on-plot/main.go:12 +0x25 fp=0xc00015fbb0 sp=0xc00015fb90 pc=0x629325
github.com/AllenDang/giu.(*CustomWidget).Build(0xc0002227a0?)
	/home/mszeptuch/git/giu/ExtraWidgets.go:308 +0x1f fp=0xc00015fbc0 sp=0xc00015fbb0 pc=0x626b1f
github.com/AllenDang/giu.Layout.Build(...)
	/home/mszeptuch/git/giu/Layout.go:28
github.com/AllenDang/giu.(*WindowWidget).Layout(0xc000177dc0, {0xc00015fc48?, 0x2, 0xc00015fc50?})
	/home/mszeptuch/git/giu/Window.go:114 +0x1ca fp=0xc00015fc08 sp=0xc00015fbc0 pc=0x628f8a
main.loop()
	/home/mszeptuch/git/giu/examples/label-on-plot/main.go:9 +0x105 fp=0xc00015fc78 sp=0xc00015fc08 pc=0x629465
github.com/AllenDang/cimgui-go.glfwWindowLoopCallback(...)
	/home/mszeptuch/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20221018030210-b4e0125a30eb/backend.go:94
_cgoexp_fd25f527374f_glfwWindowLoopCallback(0x8?)
	_cgo_gotypes.go:53206 +0x23 fp=0xc00015fc88 sp=0xc00015fc78 pc=0x59a583
runtime.cgocallbackg1(0x59a560, 0xc00015fe40?, 0x0)
	/usr/local/go/src/runtime/cgocall.go:316 +0x2c2 fp=0xc00015fd58 sp=0xc00015fc88 pc=0x4dd082
runtime.cgocallbackg(0xc0000061a0?, 0x300000002?, 0xc0000061a0?)
	/usr/local/go/src/runtime/cgocall.go:235 +0x109 fp=0xc00015fde8 sp=0xc00015fd58 pc=0x4dcd09
runtime.cgocallbackg(0x59a560, 0x7fff8b40040f, 0x0)
	<autogenerated>:1 +0x2f fp=0xc00015fe10 sp=0xc00015fde8 pc=0x53de4f
runtime.cgocallback(0x4dcb85, 0x629750, 0xc00015fea0)
	/usr/local/go/src/runtime/asm_amd64.s:994 +0xb4 fp=0xc00015fe38 sp=0xc00015fe10 pc=0x53b954
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:459 fp=0xc00015fe40 sp=0xc00015fe38 pc=0x539960
runtime.cgocall(0x629750, 0xc00015fea0)
	/usr/local/go/src/runtime/cgocall.go:168 +0x85 fp=0xc00015fe78 sp=0xc00015fe40 pc=0x4dcb85
github.com/AllenDang/cimgui-go._Cfunc_igRunLoop(0x1138b80, 0x6294d0, 0x629510, 0x629550, 0x6295d0)
	_cgo_gotypes.go:53150 +0x45 fp=0xc00015fea0 sp=0xc00015fe78 pc=0x597da5
github.com/AllenDang/cimgui-go.GLFWwindow.Run.func1(0x1138b80?)
	/home/mszeptuch/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20221018030210-b4e0125a30eb/backend.go:76 +0x9b fp=0xc00015ff00 sp=0xc00015fea0 pc=0x5980fb
github.com/AllenDang/cimgui-go.GLFWwindow.Run(0x1e0?, 0x0?)
	/home/mszeptuch/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20221018030210-b4e0125a30eb/backend.go:76 +0x37 fp=0xc00015ff18 sp=0xc00015ff00 pc=0x598037
github.com/AllenDang/giu.(*MasterWindow).Run(0x97716e?, 0xe?)
	/home/mszeptuch/git/giu/MasterWindow.go:89 +0x46 fp=0xc00015ff48 sp=0xc00015ff18 pc=0x627c26
main.main()
	/home/mszeptuch/git/giu/examples/label-on-plot/main.go:28 +0x3d fp=0xc00015ff80 sp=0xc00015ff48 pc=0x6294bd
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc00015ffe0 sp=0xc00015ff80 pc=0x5101d2
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00015ffe8 sp=0xc00015ffe0 pc=0x53bb81

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000060fb0 sp=0xc000060f90 pc=0x510596
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:302 +0xad fp=0xc000060fe0 sp=0xc000060fb0 pc=0x51042d
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000060fe8 sp=0xc000060fe0 pc=0x53bb81
created by runtime.init.6
	/usr/local/go/src/runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000061790 sp=0xc000061770 pc=0x510596
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc0000617c8 sp=0xc000061790 pc=0x4fcfee
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc0000617e0 sp=0xc0000617c8 pc=0x4f1ea6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000617e8 sp=0xc0000617e0 pc=0x53bb81
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000088000?, 0x9c53c0?, 0x1?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000061f70 sp=0xc000061f50 pc=0x510596
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.(*scavengerState).park(0xb938a0)
	/usr/local/go/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc000061fa0 sp=0xc000061f70 pc=0x4fb093
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:617 +0x45 fp=0xc000061fc8 sp=0xc000061fa0 pc=0x4fb665
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc000061fe0 sp=0xc000061fc8 pc=0x4f1e46
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000061fe8 sp=0xc000061fe0 pc=0x53bb81
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:179 +0xaa

goroutine 18 [finalizer wait]:
runtime.gopark(0xb93d60?, 0xc0001024e0?, 0x0?, 0x0?, 0xc000060770?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000060628 sp=0xc000060608 pc=0x510596
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:180 +0x10f fp=0xc0000607e0 sp=0xc000060628 pc=0x4f0faf
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000607e8 sp=0xc0000607e0 pc=0x53bb81
created by runtime.createfing
	/usr/local/go/src/runtime/mfinal.go:157 +0x45
exit status 2
```

**Comment by gucio321** [comment]
commit 5c8eb27684bd2704eeac0195ea85f64acc41e98b (HEAD -> docking, upstream/docking, origin/docking)

**Comment by pipe01** [comment]
Can confirm, any progress on this?

**Comment by gucio321** [comment]
Well, the only thing i can say for now is that it actually works in examples so need to investigate what exactly is going on here

I'll probably get here "next year" 🙂

**Comment by pipe01** [comment]
Well that's odd. I'll be waiting :smile:

**Comment by pipe01** [comment]
Nevermind, just figured it out haha. Turns out you just have to call `cimgui.Plot_CreateContext()` before any implot calls, running it before `window.Run` seems to work.

**Comment by gucio321** [comment]
Oh thank you @pipe01!
@AllenDang shall we improve cimgui anyhow, or everything is ok here and we just need to add documentation?

**Comment by AllenDang** [comment]
@gucio321 I think we should proceed to use it in giu and replace imgui-go completely. Once the migration process is done, which means cimgui-go is good enough, we could add documentation both for giu and cimgui.

**Comment by gucio321** [comment]
ok, so let me close this for now
