### ISSUE TITLE
Panic when exiting with window manager help (e.g. ALT+F4) without SetBeforeDestroyContextHook after loading own fonts

### ISSUE THREAD

**Issue by pztrn** [AllenDang/cimgui-go#90]
cimgui-go 91ad6387382a

Trying to add font from `embed.FS` like this:

```
	normalFontBytes, _ := assets.Assets.ReadFile("fonts/JetBrainsMono-Regular.ttf")
	_ = imgui.CurrentIO().Fonts().AddFontFromMemoryTTF(unsafe.Pointer(&normalFontBytes), 17, 1.0)
```

And got this:

```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
github.com/AllenDang/cimgui-go.FontAtlas.AddFontFromMemoryTTF.func1(0xc00006de50?, 0x589339?, 0x6de60?, 0x3f800000)
        /home/pztrn/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20230113051822-91ad6387382a/cimgui_funcs.go:4195 +0x5a
github.com/AllenDang/cimgui-go.FontAtlas.AddFontFromMemoryTTF(0x7fa7e424ba38?, 0x8bdb2e?, 0x1f?, 0x0?)
        /home/pztrn/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20230113051822-91ad6387382a/cimgui_funcs.go:4195 +0x19
```

**Comment by gucio321** [comment]
Maybe you need to pass punter to the first element of an array rather to the entire array

**Comment by pztrn** [comment]
That helps with font loading, yes. But when I'm closing my app:

```
free(): invalid pointer
SIGABRT: abort
PC=0x7fd8423b964c m=3 sigcode=18446744073709551610
signal arrived during cgo execution
```

Probably it's better to switch from `unsafe.Pointer` with not-so-obvious logic to pass first element of array to separate type?

**Comment by gucio321** [comment]
> Probably it's better to switch from unsafe.Pointer with not-so-obvious logic to pass first element of array to separate type?

ofc, cimgui should handle it automatically in fact, however, for some reason, it doesn't do so...

**Comment by gucio321** [comment]
oh man!
It is `void*` in C code, but... what is that xD
I mean, What should it be in GO, and, why isn't it `uint*` or something...
I need to know what usage of this function in imgui looks like, because it seems that it takes something else than just slice of font data..

**Comment by gucio321** [comment]
> That helps with font loading, yes. But when I'm closing my app:
> 
> ```
> free(): invalid pointer
> SIGABRT: abort
> PC=0x7fd8423b964c m=3 sigcode=18446744073709551610
> signal arri
> ```

@pztrn are you sure that this panic is caused by font loading?

My assume is, that there **may** be a conflict in freeing memory at the end of application run.
C code tries to free pointer to the first array index, but, (befor this happens) go has already freed the whole slice. (it is only my assume and it may be false).
Could you please post some reproducable code as it is a bit hard to debug now

**Comment by pztrn** [comment]
This is a full cimgui-go traceback which appears in loop:

```
free(): invalid pointer
SIGABRT: abort
PC=0x7f1b7d8a164c m=4 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall]:
runtime.cgocall(0x68f3a0, 0xc00012dda0)
        /usr/lib/go/src/runtime/cgocall.go:158 +0x5c fp=0xc00012dd78 sp=0xc00012dd40 pc=0x4de61c
github.com/AllenDang/cimgui-go._Cfunc_igRunLoop(0x7f1b4c084f10, 0x68f000, 0x68f070, 0x68f0e0, 0x68f1c0)
        _cgo_gotypes.go:15724 +0x45 fp=0xc00012dda0 sp=0xc00012dd78 pc=0x5e81a5
github.com/AllenDang/cimgui-go.GLFWwindow.Run.func1(0xc0000c4001?)
        /home/pztrn/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20230114045626-6621efc23dea/backend.go:77 +0x9b fp=0xc00012de00 sp=0xc00012dda0 pc=0x5e8f9b
github.com/AllenDang/cimgui-go.GLFWwindow.Run(0xc0000a01b0?, 0xc0000c4000?)
        /home/pztrn/go/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20230114045626-6621efc23dea/backend.go:77 +0x37 fp=0xc00012de18 sp=0xc00012de00 pc=0x5e8ed7
```

**Comment by pztrn** [comment]
Mkay, figured it out. This is because `imgui.SetBeforeDestroyContextHook` wasn't set to my app shutdown handler. After setting it - everything is okay, no tracebacks.

**Comment by gucio321** [comment]
commit: 12d6ead371026021b3628ab2505220836fa9d839

```diff
diff --git a/examples/main.go b/examples/main.go
index 75afab3..12ae3d2 100644
--- a/examples/main.go
+++ b/examples/main.go
@@ -3,6 +3,8 @@ package main
 import (
 	"fmt"
 	"image"
+	"os"
+	"unsafe"
 
 	imgui "github.com/AllenDang/cimgui-go"
 )
@@ -128,5 +130,8 @@ func main() {
 
 	backend.CreateWindow("Hello from cimgui-go", 1200, 900, 0)
 
+	font, _ := os.ReadFile("VL-Gothic-Regular.ttf")
+	_ = imgui.CurrentIO().Fonts().AddFontFromMemoryTTF(unsafe.Pointer(&font[0]), 17, 17.0)
+
 	backend.Run(loop)
 }
```

<details><summary>Panic</summary>

```console
munmap_chunk(): invalid pointer
SIGABRT: abort
PC=0x7f45295cfe5c m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall]:
runtime.cgocall(0x5e25e0, 0xc000073ea0)
	/usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc000073e78 sp=0xc000073e40 pc=0x4f333c
github.com/AllenDang/cimgui-go._Cfunc_igRunLoop(0x165f7f0, 0x5b2fa0, 0x5b2fe0, 0x5b3020, 0x5b30a0)
	_cgo_gotypes.go:27380 +0x45 fp=0xc000073ea0 sp=0xc000073e78 pc=0x5a4c65
github.com/AllenDang/cimgui-go.(*GLFWBackend).Run.func1(0x4188000000073f18?)
	/home/me/git/cimgui-go/glfw_backend.go:92 +0x9f fp=0xc000073f00 sp=0xc000073ea0 pc=0x5a8c5f
github.com/AllenDang/cimgui-go.(*GLFWBackend).Run(0x17e08a8?, 0x928c19?)
	/home/me/git/cimgui-go/glfw_backend.go:92 +0x33 fp=0xc000073f18 sp=0xc000073f00 pc=0x5a8b93
main.main()
	/home/me/git/cimgui-go/examples/main.go:136 +0x238 fp=0xc000073f80 sp=0xc000073f18 pc=0x5b2ef8
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x207 fp=0xc000073fe0 sp=0xc000073f80 pc=0x524627
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000073fe8 sp=0xc000073fe0 pc=0x54f061

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000060fb0 sp=0xc000060f90 pc=0x524a56
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:305 +0xb0 fp=0xc000060fe0 sp=0xc000060fb0 pc=0x524890
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000060fe8 sp=0xc000060fe0 pc=0x54f061
created by runtime.init.6
	/usr/local/go/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000061780 sp=0xc000061760 pc=0x524a56
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:319 +0xde fp=0xc0000617c8 sp=0xc000061780 pc=0x5116de
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc0000617e0 sp=0xc0000617c8 pc=0x506b66
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000617e8 sp=0xc0000617e0 pc=0x54f061
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000088000?, 0x9480c0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000061f70 sp=0xc000061f50 pc=0x524a56
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0xac4ca0)
	/usr/local/go/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000061fa0 sp=0xc000061f70 pc=0x50f5d3
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:633 +0x65 fp=0xc000061fc8 sp=0xc000061fa0 pc=0x50fbc5
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc000061fe0 sp=0xc000061fc8 pc=0x506b06
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000061fe8 sp=0xc000061fe0 pc=0x54f061
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x1a0?, 0xac50e0?, 0x60?, 0x78?, 0xc000060770?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000060628 sp=0xc000060608 pc=0x524a56
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:193 +0x107 fp=0xc0000607e0 sp=0xc000060628 pc=0x505ba7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000607e8 sp=0xc0000607e0 pc=0x54f061
created by runtime.createfing
	/usr/local/go/src/runtime/mfinal.go:163 +0x45

goroutine 6 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000062750 sp=0xc000062730 pc=0x524a56
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000627e0 sp=0xc000062750 pc=0x5086d1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000627e8 sp=0xc0000627e0 pc=0x54f061
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 18 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00005c750 sp=0xc00005c730 pc=0x524a56
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00005c7e0 sp=0xc00005c750 pc=0x5086d1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00005c7e8 sp=0xc00005c7e0 pc=0x54f061
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0005b0750 sp=0xc0005b0730 pc=0x524a56
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0005b07e0 sp=0xc0005b0750 pc=0x5086d1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005b07e8 sp=0xc0005b07e0 pc=0x54f061
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00005cf50 sp=0xc00005cf30 pc=0x524a56
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00005cfe0 sp=0xc00005cf50 pc=0x5086d1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00005cfe8 sp=0xc00005cfe0 pc=0x54f061
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00005d750 sp=0xc00005d730 pc=0x524a56
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00005d7e0 sp=0xc00005d750 pc=0x5086d1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00005d7e8 sp=0xc00005d7e0 pc=0x54f061
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 7 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000062f50 sp=0xc000062f30 pc=0x524a56
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000062fe0 sp=0xc000062f50 pc=0x5086d1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000062fe8 sp=0xc000062fe0 pc=0x54f061
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 8 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000063750 sp=0xc000063730 pc=0x524a56
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000637e0 sp=0xc000063750 pc=0x5086d1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000637e8 sp=0xc0000637e0 pc=0x54f061
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 9 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000063f50 sp=0xc000063f30 pc=0x524a56
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000063fe0 sp=0xc000063f50 pc=0x5086d1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000063fe8 sp=0xc000063fe0 pc=0x54f061
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 10 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0005ac750 sp=0xc0005ac730 pc=0x524a56
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0005ac7e0 sp=0xc0005ac750 pc=0x5086d1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005ac7e8 sp=0xc0005ac7e0 pc=0x54f061
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 11 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0005acf50 sp=0xc0005acf30 pc=0x524a56
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0005acfe0 sp=0xc0005acf50 pc=0x5086d1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005acfe8 sp=0xc0005acfe0 pc=0x54f061
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 12 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0005ad750 sp=0xc0005ad730 pc=0x524a56
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0005ad7e0 sp=0xc0005ad750 pc=0x5086d1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005ad7e8 sp=0xc0005ad7e0 pc=0x54f061
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 13 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0005adf50 sp=0xc0005adf30 pc=0x524a56
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0005adfe0 sp=0xc0005adf50 pc=0x5086d1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005adfe8 sp=0xc0005adfe0 pc=0x54f061
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 14 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0005ae750 sp=0xc0005ae730 pc=0x524a56
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0005ae7e0 sp=0xc0005ae750 pc=0x5086d1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005ae7e8 sp=0xc0005ae7e0 pc=0x54f061
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 15 [GC worker (idle)]:
runtime.gopark(0xce6d20?, 0x1?, 0xe?, 0x45?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0005aef50 sp=0xc0005aef30 pc=0x524a56
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0005aefe0 sp=0xc0005aef50 pc=0x5086d1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005aefe8 sp=0xc0005aefe0 pc=0x54f061
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 16 [GC worker (idle)]:
runtime.gopark(0xce6d20?, 0x1?, 0x6?, 0x6b?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0005af750 sp=0xc0005af730 pc=0x524a56
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0005af7e0 sp=0xc0005af750 pc=0x5086d1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005af7e8 sp=0xc0005af7e0 pc=0x54f061
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 50 [GC worker (idle)]:
runtime.gopark(0xce6d20?, 0x1?, 0xaf?, 0x43?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0005aff50 sp=0xc0005aff30 pc=0x524a56
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0005affe0 sp=0xc0005aff50 pc=0x5086d1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005affe8 sp=0xc0005affe0 pc=0x54f061
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

rax    0x0
rbx    0xe1b3
rcx    0x7f45295cfe5c
rdx    0x6
rdi    0xe1b3
rsi    0xe1b3
rbp    0x7f452942a740
rsp    0x7ffc608d1040
r8     0xffffffff
r9     0x0
r10    0x8
r11    0x246
r12    0x6
r13    0x7f44f3411000
r14    0x1
r15    0x1
rip    0x7f45295cfe5c
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
exit status 2
```

</details>

**Comment by gucio321** [comment]
when looking at ChatGPT, I started to believe that it may be related to GO memory management. Let me quote the chat:
> This error message usually indicates a memory corruption issue in a C or C++ program. The error message is indicating that an invalid pointer was passed to the munmap_chunk() function, which is typically used to free dynamically allocated memory.
> 
> A possible reason for this error could be that the memory being freed has already been freed before or was not allocated using the appropriate allocation function, resulting in the invalid pointer.

**Comment by gucio321** [comment]
As of my research I can say the following:
- panic appears because font `data` byte slice (created later in code pointer to it) is removed by GC (Garbage Collector)
- In imgui C code there is  DestroyCOntext (or something like that - could be checked by using gdb) that attempts to free this font data but it fails because it is allready released
- might be related to #184 (void* pointer management - created unsafe.Pointer should be pinned via runtime.Pinner)

**Comment by gucio321** [comment]
@pztrn I figured it out!
You have to set `FontDataOwnedByAtlas` (field of FontConfig) to `false`. Then there is no conflict between GO's GC and imgui's DestroyContext.

**Comment by gucio321** [comment]
Also, you can use runtime.Pinner to pin pointer before passing to cimgui-go. Then it shouldn't panic because GC should leav it.
